USE [master]
GO
CREATE DATABASE [ACS_Archive]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ACS_Archive', FILENAME = N'D:\SQLData\ACS_Archive.mdf' , SIZE = 1048576KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ACS_Archive_log', FILENAME = N'D:\SQLLog\ACS_Archive_log.ldf' , SIZE = 524288KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 COLLATE SQL_Latin1_General_CP1_CI_AS
GO
ALTER DATABASE [ACS_Archive] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ACS_Archive].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ACS_Archive] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ACS_Archive] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ACS_Archive] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ACS_Archive] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ACS_Archive] SET ARITHABORT OFF 
GO
ALTER DATABASE [ACS_Archive] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ACS_Archive] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ACS_Archive] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ACS_Archive] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ACS_Archive] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ACS_Archive] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ACS_Archive] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ACS_Archive] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ACS_Archive] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ACS_Archive] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ACS_Archive] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ACS_Archive] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ACS_Archive] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ACS_Archive] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ACS_Archive] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ACS_Archive] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ACS_Archive] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ACS_Archive] SET RECOVERY FULL 
GO
ALTER DATABASE [ACS_Archive] SET  MULTI_USER 
GO
ALTER DATABASE [ACS_Archive] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ACS_Archive] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ACS_Archive] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ACS_Archive] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ACS_Archive] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [ACS_Archive] SET QUERY_STORE = OFF
GO
USE [ACS_Archive]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
GRANT VIEW ANY COLUMN ENCRYPTION KEY DEFINITION TO [public] AS [dbo]
GO
GRANT VIEW ANY COLUMN MASTER KEY DEFINITION TO [public] AS [dbo]
GO
ALTER DATABASE [ACS_Archive] SET  READ_WRITE 
GO
