USE [ACS_Archive]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[dtString](
	[Id] [int] NOT NULL,
	[PartitionId] [nchar](36) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[TypeId] [int] NOT NULL,
	[DescHash] [binary](20) NOT NULL,
	[Description] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
 CONSTRAINT [pkString] PRIMARY KEY CLUSTERED 
(
	[Id] ASC,
	[PartitionId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[dtString]  WITH CHECK ADD  CONSTRAINT [fkStringType] FOREIGN KEY([TypeId])
REFERENCES [dbo].[dtType] ([Id])
GO
ALTER TABLE [dbo].[dtString] CHECK CONSTRAINT [fkStringType]
GO
